// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.29.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'streamer_model.dart';

Future<StreamerVideoResponse> getVideos({required String url, dynamic hint}) =>
    RustLib.instance.api.getVideos(url: url, hint: hint);

Future<StreamersResponse> getCategory(
        {required StreamerType type, dynamic hint}) =>
    RustLib.instance.api.getCategory(type: type, hint: hint);

Future<StreamerVideoResponse> getMoreVideos(
        {required String url, dynamic hint}) =>
    RustLib.instance.api.getMoreVideos(url: url, hint: hint);
